### ISSUE TITLE
Cấu trúc thư mục

### ISSUE THREAD

**Issue by tuanlaRikkeisoft** [tuanlaRikkeisoft/SwiftTraining#1]
Cần câu trúc project thành các thư mục thực:

- [ ] hiện tại các file đươc để chung 1 thư mục project trông khá lộn xộn

- [ ] với các project có nhiều file cần nhóm các file vào thư mục riêng, có thể theo mô hình MVC hoặc 1 mô hình phù hợp khác

**Comment by nguyenminhtienhust** [comment]
Vâng. Vì lúc làm xcode của e bị lỗi ko add đc thư mục , nên e chỉ tạo đc group vật lý. giờ e đã sửa lại.
